import { cp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parseCSV } from '../src/data.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const dist = path.join(root, 'dist');
const source = path.resolve(root, '../../experiments/btc-regime-validation/sources/btc-usd-bitstamp.csv');
const parsed = parseCSV(await readFile(source, 'utf8'));
await rm(dist, { recursive: true, force: true });
await mkdir(path.join(dist, 'vendor'), { recursive: true });
for (const file of ['index.html', 'styles.css']) await cp(path.join(root, file), path.join(dist, file));
await cp(path.join(root, 'src'), path.join(dist, 'src'), { recursive: true });
await cp(source, path.join(dist, 'btc-usd.csv'));
const library = path.dirname(fileURLToPath(import.meta.resolve('lightweight-charts')));
await cp(path.join(library, 'lightweight-charts.standalone.production.mjs'), path.join(dist, 'vendor/charts.mjs'));
await cp(path.join(library, '..', 'LICENSE'), path.join(dist, 'vendor/LICENSE'));
await cp(path.join(root, 'NOTICE'), path.join(dist, 'vendor/NOTICE'));
await writeFile(path.join(dist, 'data-info.json'), JSON.stringify({ ...parsed.metadata, first: parsed.candles[0].time, last: parsed.candles.at(-1).time, count: parsed.candles.length }, null, 2));
console.log(`Built Investment Lab: ${parsed.candles.length} daily candles through ${parsed.candles.at(-1).time}`);
